development:
  update_database_job:
    cron: '0 8 * * *'
    class: 'UpdateDatabaseJob'
    queue: 'auto_updates'

sandbox:
  update_database_job:
    cron: '0 8 * * *'
    class: 'UpdateDatabaseJob'
    queue: 'auto_updates'

production:
  update_database_job:
    cron: '0 2 * * *'
    class: 'UpdateDatabaseJob'
    queue: 'auto_updates'

# à supprimer à partir d'ici
# pour ne pas utiliser l'API de l'INSEE
  daily_update_job:
    cron: '0 5 * * *'
    class: 'DailyUpdateJob'
    queue: 'auto_updates'
